In [1]:
import pandas as pd

In [11]:
df_covet = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/covetcrystalsjewelry.csv")
df_crystlmojo = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/crystalmojo.csv")
df_fateditis = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/fated.itis.csv")
df_gemstory = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/gemstorysg.csv")
df_glacecrystals = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/glacecrystals.csv")
df_illanocte = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/illa_nocte.csv")
df_kaylacrystals = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/kayla.crystals.csv")
df_loveforcrystals = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/loveforcrystals.csv")
df_ohmou = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/ohmou.sg.csv")
df_soulalign = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/soulalign.csv")
df_tamza = pd.read_csv("raw-data/instagram/social-netork/competitors_details/2.0/tamzacrystals.csv")
df_jamstones = pd.read_csv("raw-data/instagram/js-posts-all/optimal_post_timing2.0.csv")

In [13]:
df_combined = pd.concat([df_covet, df_crystlmojo, df_fateditis, df_gemstory, df_glacecrystals, df_illanocte, df_kaylacrystals, df_loveforcrystals, df_ohmou, df_soulalign, df_tamza, df_jamstones], keys=["covet","crystalmojo","fateditis","gemstory","glacecrystals","illanocte","kaylacrystals","loveforcrystals","ohmou","soulalign","tamza", "jamstones"], )

In [15]:
df_combined.head(200)

           Unnamed: 0  index                 date  \
covet 0             0      0  2022-03-30 11:48:36
      1             1      1  2022-03-29 23:45:55
      2             2      2  2022-03-29 17:02:06
      3             3      3  2022-03-29 08:51:07
      4             4      4  2022-03-28 23:45:51
...               ...    ...                  ...
      195         195    195  2022-02-08 17:05:38
      196         196    196  2022-02-08 14:54:54
      197         197    197  2022-02-07 21:03:45
      198         198    198  2022-02-07 21:02:16
      199         199    199  2022-02-07 21:01:21

                                                     caption  comments  likes
covet 0    The bags get swag too❤️\r\nLucky Coins Jade ba...         0      6
      1    <SOLD> Garden Phantom Quartz  Supreme and Gard...         0     11
      2    <SOLD> Garden Phantom Quartz  Supreme and Gard...         0     10
      3    <SOLD> Garden Phantom Quartz  Supreme and Gard...         0     17
      4    <SOLD> Autumn & Winter Phantom Quartz and Whit...         0      8
...                                                      ...       ...    ...
      195  New diadem jewelry featuring Jade Amazonite, S...         0      3
      196  New diadem jewelry featuring Jade Amazonite, S...         0      3
      197  Spring Treasure Diadem Bracelet. \r\nMade with...         0      2
      198  Spring Treasure Diadem Bracelet. \r\nMade with...         0      3
      199  Spring Treasure Diadem Bracelet. \r\nMade with...         0      3

[200 rows x 6 columns]

In [16]:
df_combined.reset_index(inplace=True)

In [17]:
df_combined

,level_0,level_1,Unnamed: 0,index,date,caption,comments,likes
0,covet,0,0,0,2022-03-30 11:48:36,The bags get swag too❤️\r\nLucky Coins Jade ba...,0,6
1,covet,1,1,1,2022-03-29 23:45:55,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,11
2,covet,2,2,2,2022-03-29 17:02:06,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,10
3,covet,3,3,3,2022-03-29 08:51:07,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,17
4,covet,4,4,4,2022-03-28 23:45:51,<SOLD> Autumn & Winter Phantom Quartz and Whit...,0,8
...,...,...,...,...,...,...,...,...
12047,jamstones,598,598,598,2020-04-12 21:05:29,A Z U R E\r\n\r\n#crystals #crystaljewelry #sh...,0,21
12048,jamstones,599,599,599,2020-04-12 21:04:33,A Q U A R I U S \r\n#crystals #crystaljewelry ...,0,22
12049,jamstones,600,600,600,2020-04-12 21:01:14,A V E R Y\r\n\r\n#crystals #crystaljewelry #sh...,0,22
12050,jamstones,601,601,601,2020-04-12 21:00:31,A R T I C\r\n\r\n#crystals #crystaljewelry #sh...,0,22
12051,jamstones,602,602,602,2020-04-12 20:59:08,A R T E M I S\r\n#crystals #crystaljewelry #sh...,0,23

In [18]:
df_combined = df_combined.drop(columns=["Unnamed: 0", "level_1"])

In [19]:
df_combined

,level_0,index,date,caption,comments,likes
0,covet,0,2022-03-30 11:48:36,The bags get swag too❤️\r\nLucky Coins Jade ba...,0,6
1,covet,1,2022-03-29 23:45:55,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,11
2,covet,2,2022-03-29 17:02:06,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,10
3,covet,3,2022-03-29 08:51:07,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,17
4,covet,4,2022-03-28 23:45:51,<SOLD> Autumn & Winter Phantom Quartz and Whit...,0,8
...,...,...,...,...,...,...
12047,jamstones,598,2020-04-12 21:05:29,A Z U R E\r\n\r\n#crystals #crystaljewelry #sh...,0,21
12048,jamstones,599,2020-04-12 21:04:33,A Q U A R I U S \r\n#crystals #crystaljewelry ...,0,22
12049,jamstones,600,2020-04-12 21:01:14,A V E R Y\r\n\r\n#crystals #crystaljewelry #sh...,0,22
12050,jamstones,601,2020-04-12 21:00:31,A R T I C\r\n\r\n#crystals #crystaljewelry #sh...,0,22
12051,jamstones,602,2020-04-12 20:59:08,A R T E M I S\r\n#crystals #crystaljewelry #sh...,0,23

In [20]:
df_combined_no_giveaway = df_combined[df_combined["caption"].str.contains("giveaway") == False]

In [21]:
df_combined_no_giveaway

,level_0,index,date,caption,comments,likes
0,covet,0,2022-03-30 11:48:36,The bags get swag too❤️\r\nLucky Coins Jade ba...,0,6
1,covet,1,2022-03-29 23:45:55,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,11
2,covet,2,2022-03-29 17:02:06,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,10
3,covet,3,2022-03-29 08:51:07,<SOLD> Garden Phantom Quartz Supreme and Gard...,0,17
4,covet,4,2022-03-28 23:45:51,<SOLD> Autumn & Winter Phantom Quartz and Whit...,0,8
...,...,...,...,...,...,...
12047,jamstones,598,2020-04-12 21:05:29,A Z U R E\r\n\r\n#crystals #crystaljewelry #sh...,0,21
12048,jamstones,599,2020-04-12 21:04:33,A Q U A R I U S \r\n#crystals #crystaljewelry ...,0,22
12049,jamstones,600,2020-04-12 21:01:14,A V E R Y\r\n\r\n#crystals #crystaljewelry #sh...,0,22
12050,jamstones,601,2020-04-12 21:00:31,A R T I C\r\n\r\n#crystals #crystaljewelry #sh...,0,22
12051,jamstones,602,2020-04-12 20:59:08,A R T E M I S\r\n#crystals #crystaljewelry #sh...,0,23

In [25]:
df_combined_no_giveaway.groupby("level_0").mean().sort_values("likes", ascending=False)

                       index   comments       likes
level_0
crystalmojo       105.500000   4.259434  177.858491
illanocte         140.992593  10.992593  134.240741
glacecrystals     389.629879   3.651413  103.738896
ohmou             180.178273   6.047354  103.103064
kaylacrystals      55.910714   2.125000   93.294643
jamstones         297.780612   3.574830   72.227891
tamza              56.500000   1.140351   70.596491
soulalign         260.000000   2.523992   52.758157
fateditis         113.159292   1.495575   52.699115
gemstory          467.341202   0.809013   22.026824
covet            3042.061739   1.284821   18.800296
loveforcrystals   879.890954   0.141884    7.815366

In [26]:
df_combined_no_giveaway.to_csv("competitors against Jamstones.csv")