In [12]:
import pandas as pd
import numpy as np
import json

In [18]:
df = pd.read_csv('JS_Followers_Info/JS_followers_info_total.csv')

In [19]:
df.head()

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
0,0,gwengwenn,132.0,851.0,True,6.446970,9.0
1,1,huimin_c,365.0,439.0,True,1.202740,23.0
2,2,agent_g07,26.0,755.0,True,29.038462,200.0
3,3,agnestankimpheng,84.0,583.0,False,6.940476,7.0
4,4,umareumm,3900.0,464.0,True,0.118974,87.0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13406 entries, 0 to 13405
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       13406 non-null  object
 1   follower         13405 non-null  object
 2   no_of_followers  13405 non-null  float64
 3   no_of_followees  13405 non-null  float64
 4   is_private       13405 non-null  object
 5   ratio            13405 non-null  float64
 6   no_of_posts      13405 non-null  float64
dtypes: float64(4), object(3)
memory usage: 733.3+ KB

In [16]:
df.drop_duplicates("follower", inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13387 entries, 0 to 13405
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       13387 non-null  object
 1   follower         13386 non-null  object
 2   no_of_followers  13386 non-null  float64
 3   no_of_followees  13386 non-null  float64
 4   is_private       13386 non-null  object
 5   ratio            13386 non-null  float64
 6   no_of_posts      13386 non-null  float64
dtypes: float64(4), object(3)
memory usage: 836.7+ KB

In [21]:
filtered_df = df[df["is_private"] == False]
filtered_df

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
3,3,agnestankimpheng,84.0,583.0,False,6.940476,7.0
11,11,ekitty27,96.0,175.0,False,1.822917,58.0
12,12,pohjaslin,535.0,454.0,False,0.848598,777.0
13,13,bloatofhippos,218.0,344.0,False,1.577982,106.0
17,17,eileen.symrise,131.0,61.0,False,0.465649,1.0
...,...,...,...,...,...,...,...
13379,13379,samanthasweets_,1077.0,2216.0,False,2.057567,3119.0
13384,13384,sharifah919,1896.0,5510.0,False,2.906118,80.0
13390,13390,queenietay,296.0,252.0,False,0.851351,637.0
13397,13397,dionysus_and_diana,2.0,22.0,False,11.000000,0.0
13403,13403,stylebyjane,1325.0,1033.0,False,0.779623,102.0

In [22]:
filtered_df = filtered_df[filtered_df["ratio"] < 1]
filtered_df

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
12,12,pohjaslin,535.0,454.0,False,0.848598,777.0
17,17,eileen.symrise,131.0,61.0,False,0.465649,1.0
18,18,yemafrnndz,1038.0,677.0,False,0.652216,10.0
25,25,pohjaslin,535.0,454.0,False,0.848598,777.0
30,30,eileen.symrise,131.0,61.0,False,0.465649,1.0
...,...,...,...,...,...,...,...
13366,13366,karenacyp,2153.0,570.0,False,0.264747,1278.0
13367,13367,pandajoyce,2503.0,2209.0,False,0.882541,528.0
13374,13374,limbeeling,94.0,59.0,False,0.627660,92.0
13390,13390,queenietay,296.0,252.0,False,0.851351,637.0
13403,13403,stylebyjane,1325.0,1033.0,False,0.779623,102.0

In [23]:
filtered_df = filtered_df[filtered_df["no_of_posts"] > 1]
filtered_df

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
12,12,pohjaslin,535.0,454.0,False,0.848598,777.0
18,18,yemafrnndz,1038.0,677.0,False,0.652216,10.0
25,25,pohjaslin,535.0,454.0,False,0.848598,777.0
31,31,yemafrnndz,1038.0,677.0,False,0.652216,10.0
45,45,jasmineanggm,322.0,266.0,False,0.826087,51.0
...,...,...,...,...,...,...,...
13366,13366,karenacyp,2153.0,570.0,False,0.264747,1278.0
13367,13367,pandajoyce,2503.0,2209.0,False,0.882541,528.0
13374,13374,limbeeling,94.0,59.0,False,0.627660,92.0
13390,13390,queenietay,296.0,252.0,False,0.851351,637.0
13403,13403,stylebyjane,1325.0,1033.0,False,0.779623,102.0

In [24]:
filtered_df.sort_values(by=['no_of_followers'], ascending=False, inplace=True)
filtered_df

C:\Users\wslee.2019\Anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
13049,13049,crystalzrus,142184.0,481.0,False,0.003383,1228.0
4288,4288,happiescrappie,81650.0,1369.0,False,0.016767,150.0
1206,1206,you_yi,45157.0,3236.0,False,0.071661,2283.0
9936,9936,orangeholicsanonymous,40618.0,1108.0,False,0.027279,835.0
8611,8611,melissajaneferosha,35847.0,1996.0,False,0.055681,3210.0
...,...,...,...,...,...,...,...
4309,4309,broqueestudio,23.0,16.0,False,0.695652,4.0
10187,10187,augustinecck,21.0,20.0,False,0.952381,4.0
5186,5186,phileocollezione,20.0,7.0,False,0.350000,63.0
8308,8308,elysian_lunette,16.0,10.0,False,0.625000,6.0
4170,4170,babybrawler,6.0,4.0,False,0.666667,22.0

In [25]:
filtered_df = filtered_df[filtered_df["no_of_followers"] > 500]
filtered_df

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
13049,13049,crystalzrus,142184.0,481.0,False,0.003383,1228.0
4288,4288,happiescrappie,81650.0,1369.0,False,0.016767,150.0
1206,1206,you_yi,45157.0,3236.0,False,0.071661,2283.0
9936,9936,orangeholicsanonymous,40618.0,1108.0,False,0.027279,835.0
8611,8611,melissajaneferosha,35847.0,1996.0,False,0.055681,3210.0
...,...,...,...,...,...,...,...
8743,8743,heyoka.alchemy,517.0,504.0,False,0.974855,77.0
1574,1574,mistysanddunes,513.0,464.0,False,0.904483,182.0
13264,13264,thenoirlotus,509.0,321.0,False,0.630648,227.0
9375,9375,lilyautumn.k,507.0,485.0,False,0.956607,29.0
5464,5464,adieublackbird,501.0,445.0,False,0.888224,437.0

In [26]:
filtered_df = filtered_df[filtered_df["no_of_followers"] > 1000]
filtered_df

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
13049,13049,crystalzrus,142184.0,481.0,False,0.003383,1228.0
4288,4288,happiescrappie,81650.0,1369.0,False,0.016767,150.0
1206,1206,you_yi,45157.0,3236.0,False,0.071661,2283.0
9936,9936,orangeholicsanonymous,40618.0,1108.0,False,0.027279,835.0
8611,8611,melissajaneferosha,35847.0,1996.0,False,0.055681,3210.0
...,...,...,...,...,...,...,...
7193,7193,julinantwt,1012.0,862.0,False,0.851779,982.0
8725,8725,min.x.xx,1010.0,998.0,False,0.988119,3653.0
10168,10168,atelier.nanae.iwami,1008.0,845.0,False,0.838294,248.0
4259,4259,quaint.daint,1007.0,291.0,False,0.288977,30.0
4873,4873,siyingx3,1006.0,861.0,False,0.855865,699.0

In [27]:
filtered_df = filtered_df[filtered_df["no_of_followers"] < 20000]
filtered_df

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
13119,13119,thekawaiisugarnspice,18790.0,7210.0,False,0.383715,996.0
11772,11772,acupofdee,18678.0,2685.0,False,0.143752,11872.0
12764,12764,n.ikolah,18285.0,582.0,False,0.031829,898.0
3628,3628,joddessss,17984.0,676.0,False,0.037589,555.0
6197,6197,limmyssg,17753.0,7504.0,False,0.422689,1397.0
...,...,...,...,...,...,...,...
7193,7193,julinantwt,1012.0,862.0,False,0.851779,982.0
8725,8725,min.x.xx,1010.0,998.0,False,0.988119,3653.0
10168,10168,atelier.nanae.iwami,1008.0,845.0,False,0.838294,248.0
4259,4259,quaint.daint,1007.0,291.0,False,0.288977,30.0
4873,4873,siyingx3,1006.0,861.0,False,0.855865,699.0

In [28]:
filtered_df = filtered_df[filtered_df["no_of_posts"] > 100]
filtered_df

,Unnamed: 0,follower,no_of_followers,no_of_followees,is_private,ratio,no_of_posts
13119,13119,thekawaiisugarnspice,18790.0,7210.0,False,0.383715,996.0
11772,11772,acupofdee,18678.0,2685.0,False,0.143752,11872.0
12764,12764,n.ikolah,18285.0,582.0,False,0.031829,898.0
3628,3628,joddessss,17984.0,676.0,False,0.037589,555.0
6197,6197,limmyssg,17753.0,7504.0,False,0.422689,1397.0
...,...,...,...,...,...,...,...
3852,3852,wangg.ch_,1020.0,796.0,False,0.780392,245.0
7193,7193,julinantwt,1012.0,862.0,False,0.851779,982.0
8725,8725,min.x.xx,1010.0,998.0,False,0.988119,3653.0
10168,10168,atelier.nanae.iwami,1008.0,845.0,False,0.838294,248.0
4873,4873,siyingx3,1006.0,861.0,False,0.855865,699.0

In [ ]:
filtered_df.to_csv("JS_followers_info_possible_candidates.csv", index=False)